package com.opensetlist.app

object AppStrings {
    val appName = "OpenSetlist"

    val cancel = "Cancelar"
    val save = "Salvar"
    val delete = "Excluir"
    val create = "Criar"
    val close = "Fechar"
    val name = "Nome"
    val back = "Voltar"
    val menu = "Menu"

    val allSongsTitle = "Todas as Músicas"
    val setlistsTitle = "Set Lists"
    val artistsTitle = "Artistas"
    val tagsTitle = "Tags"
    val settingsTitle = "Configurações"
    val editSongTitle = "Editar Música"

    val searchSongsPlaceholder = "Buscar músicas e setlists..."
    val searchSetlistsPlaceholder = "Buscar setlist por nome ou local..."
    val searchArtistsPlaceholder = "Buscar artistas..."
    val searchTagsPlaceholder = "Buscar tags..."
    val searchInSongPlaceholder = "Buscar no texto..."
    val setlistsHeader = "SETLISTS"
    val songsHeader = "MÚSICAS"

    val noSetlistsYet = "Nenhuma setlist ainda"
    val noSetlistsFound = "Nenhuma setlist encontrada"
    val emptySetlist = "Setlist vazia"
    val dragToReorderHint = "Toque e arraste para reordenar as músicas."
    val allSongsInSetlist = "Todas as músicas já estão nesta setlist."
    val noArtists = "Nenhum artista cadastrado"
    val noTags = "Nenhuma tag cadastrada"
    val noSetlistsCreatedYet = "Nenhuma setlist criada ainda."
    val noSongsOfArtist = "Nenhuma música deste artista"
    val noSongsWithTag = "Nenhuma música com esta tag"

    val titleLabel = "Título"
    val artistLabel = "Artista"
    val keyLabel = "Tom"
    val bpmLabel = "BPM"
    val capoLabel = "Capo"
    val durationLabel = "Duração"
    val youtubeLinkLabel = "Link do YouTube"
    val bodyLabel = "Letra / Cifra (ChordPro)"

    val durationPlaceholder = "3:45"
    val youtubePlaceholder = "https://youtube.com/watch?v=..."
    val datePlaceholder = "ex.: 12/05/2026"
    val locationPlaceholder = "ex.: Bar do Zé"
    val timePlaceholder = "ex.: 20:30"
    val dateLabel = "Data"
    val locationLabel = "Local"
    val timeLabel = "Horário"
    val newTagPlaceholder = "Nova tag"

    val newSong = "Nova música"
    val newSetlist = "Nova setlist"
    val newArtist = "Novo artista"
    val newTag = "Nova tag"
    val addSong = "Adicionar música"
    val addSongs = "Adicionar músicas"
    val editSetlist = "Editar setlist"
    val editArtist = "Editar artista"
    val editTag = "Editar tag"
    val editGigInfo = "Editar dados da Gig"
    val renameSetlist = "Renomear setlist"
    val renameArtist = "Renomear artista"
    val renameTag = "Renomear tag"
    val deleteSetlist = "Excluir setlist"
    val deleteArtist = "Excluir artista"
    val deleteTag = "Excluir tag"
    val shareSetlist = "Compartilhar setlist"
    val reorder = "Reordenar"
    val removeFromSetlist = "Remover da setlist"
    val addTag = "Adicionar tag"
    val importPro = "Importar .pro"
    val exportPro = "Exportar .pro"
    val search = "Buscar"
    val edit = "Editar"
    val moreOptions = "Mais opções"
    val viewOnYoutube = "Ver no YouTube"
    val previous = "Anterior"
    val next = "Próximo"
    val transposeMinusOne = "Transpor -1"
    val transposePlusOne = "Transpor +1"
    val decreaseFont = "Diminuir letra"
    val increaseFont = "Aumentar letra"
    val showChords = "Mostrar acordes"
    val hideChords = "Ocultar acordes"
    val autoScroll = "Rolagem automática"
    val pedalBluetooth = "Pedal Bluetooth"
    val speedLabel = "Velocidade:"
    val decreaseSpeed = "Diminuir velocidade"
    val increaseSpeed = "Aumentar velocidade"

    val sortNameAsc = "Nome (A-Z)"
    val sortNameDesc = "Nome (Z-A)"
    val sortArtistAsc = "Artista (A-Z)"
    val sortArtistDesc = "Artista (Z-A)"
    val sortCreatedAsc = "Criação (antigas)"
    val sortCreatedDesc = "Criação (recentes)"
    val sortLocationAsc = "Local (A-Z)"
    val sortLocationDesc = "Local (Z-A)"
    val sortDateAsc = "Data (crescente)"
    val sortDateDesc = "Data (decrescente)"
    val sortSongsAsc = "Menos músicas"
    val sortSongsDesc = "Mais músicas"

    val restoreBackup = "Restaurar backup"
    val restoreBackupConfirm = "Isso substituirá todos os dados atuais pelos dados do backup. Continuar?"
    val restore = "Restaurar"

    val backupDbTitle = "Backup do banco de dados"
    val exportFullBackup = "Exportar backup completo (.db)"
    val exportFullBackupSubtitle = "Copia o banco SQLite inteiro, pronto para uso externo"
    val importBackup = "Importar backup (.db)"
    val importBackupSubtitle = "Restaura todos os dados a partir de um arquivo .db"
    val songsSectionTitle = "Músicas"
    val exportAllSongs = "Exportar todas as músicas"
    val importSongsBatch = "Importar músicas (em lote)"
    val setlistHelperTitle = "SetList Helper"
    val importSetlistHelper = "Importar backup do SetList Helper"
    val importSetlistHelperSubtitle = "Restaura músicas e setlists de um backup .db"
    val importSharedSetlist = "Importar setlist compartilhada"

    val saveBackupToFile = "Salvar backup em arquivo"
    val shareBackup = "Compartilhar backup"
    val importBackupFile = "Importar backup"
    val saveSongsToFile = "Salvar músicas em arquivo"
    val shareSongs = "Compartilhar músicas"
    val importSongs = "Importar músicas"
    val importSetlistHelperFile = "Importar backup do SetList Helper"
    val importSetlist = "Importar setlist"

    val fileSaved = "Arquivo salvo"
    val fileSaveFailed = "Falha ao salvar arquivo"
    val contentShared = "Conteúdo compartilhado"
    val invalidBackupFile = "Arquivo de backup inválido"
    val invalidSongsFile = "Arquivo de músicas inválido"
    val invalidSetlistFile = "Arquivo de setlist inválido"
    val invalidDbFile = "Arquivo .db inválido ou não é um backup deste app"
    val dbReadFailed = "Falha ao ler o banco de dados"
    val backupRestored = "Backup restaurado com sucesso"
    val invalidOrEmptyBackup = "Backup inválido ou vazio"
    val slhImportFailed = "Falha ao importar backup do SetList Helper"

    val untitledSong = "Música sem título"
    val unknownArtist = "Artista desconhecido"
    val newSongTitle = "Nova música"
    val defaultArtistName = "Artista"
    val importedSetlistName = "Setlist importada"

    val deleteConfirmation = "Excluir \"%s\"?"
    val deleteArtistWithSongs = "Excluir também as %d músicas deste artista"

    val durationUnitHour = "h"
    val durationUnitMinute = "min"
    val durationUnitSecond = "s"

    val metaTom = "Tom"
    val metaTempo = "Tempo"
    val metaCompasso = "Compasso"
    val metaDuracao = "Duração"
    val metaCapo = "Capo"
    val metaCompositor = "Compositor"
    val metaLetra = "Letra"
    val metaAlbum = "Álbum"
    val metaAno = "Ano"
    val metaTags = "Tags"

    fun editSongTitle(name: String) = "Editar $name"
    fun songsCount(count: Int) = "$count músicas"
    fun setlistsCount(count: Int) = "$count setlists"
    fun artistsCount(count: Int) = "$count artistas"
    fun tagsCount(count: Int) = "$count tags"
    fun songsImported(count: Int) = "$count músicas importadas"
    fun setlistImported(name: String) = "Setlist \"$name\" importada"
    fun slhImported(songCount: Int, setCount: Int) =
        "Importadas $songCount músicas e $setCount setlists do SetList Helper"
    fun shareSetlistName(name: String) = "Compartilhar $name"
    fun metaKeyValue(label: String, value: String) = "$label: $value"
}
